apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.2.0
    chart: grafana
    helm:
      values: |
        ingress: 
          annotations: 
            alb.ingress.kubernetes.io/target-type: ip 
          enabled: true
          ingressClassName: alb
        # assertNoLeakedSecrets: false
        # envFromSecret: postgres
        grafana.ini:
          # database:
          #   type: postgres
          #   name: "grafana"
          #   user: "grafana"
          #   password: "StrongGrafanaPass123"
          #   host: postgresql.postgresql:5432
          #   ssl_mode: disable 

          # auth:
          #   enabled: true
          #   name: Keycloak-OAuth
          #   allow_sign_up: true
          #   client_id: grafana-oauth
          #   client_secret: YOUR_APP_CLIENT_SECRET
          #   scopes: openid email profile offline_access roles
          #   email_attribute_path: email
          #   login_attribute_path: username
          #   name_attribute_path: full_name
          #   auth_url: https://keycloak-demo.grafana.org/realms/grafan/protocol/openid-connect/auth?kc_idp_hint=google
          #   token_url: https://keycloak-demo.grafana.org/realms/grafana/protocol/openid-connect/token
          #   api_url: https://keycloak-demo.grafana.org/realms/grafana/protocol/openid-connect/userinfo
          #   role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

        persistence:
          enabled: true
          size: "1Gi"
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true



