# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mimir-distributed
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: mimir-distributed
#     repoURL: https://grafana.github.io/helm-charts
#     targetRevision: 6.1.0-weekly.368
#     helm:
#       values: |
#         serviceAccount: 
#           annotations: 
#             eks.amazonaws.com/role-arn: arn:aws:iam::313616258649:role/mimir-role
#           name: mimir-sa
#         mimir:
#           structuredConfig:
#             common:
#               storage:
#                 backend: s3
#                 s3:
#                   endpoint: s3.us-east-1.amazonaws.com
#                   region: us-east-1
#             blocks_storage:
#               s3:
#                 bucket_name: mimir-blocks-am

#             alertmanager_storage:
#               s3:
#                 bucket_name: mimir-alertmanager-am

#             ruler_storage:
#               s3:
#                 bucket_name: mimir-ruler-am
#             limits:
#               # Delete from storage metrics data older than 1 year.
#               compactor_blocks_retention_period: 1y 
#         gateway:
#           resources:
#             requests:  
#               cpu: 100m
#               memory: 512Mi
#           autoscaling:
#             enabled: true
#             minReplicas: 1
#             maxReplicas: 2
#             targetCPUUtilizationPercentage: 10
#           service:
#             type: LoadBalancer
#           ingress:
#             enabled: true
#             ingressClassName: alb 
#             hosts:
#               - host: mimir.devopslab.com
#                 paths:
#                   - path: /
#                     pathType: Prefix
#         store_gateway:
#           zoneAwareReplication:
#             enabled: false
#           persistentVolume:
#             size: 1Gi
#             storageClass: gp2
#         ingester:
#           zoneAwareReplication:
#             enabled: false
#           persistentVolume:
#             size: 1Gi
#             storageClass: gp2

#         alertmanager:
#           zoneAwareReplication:
#             enabled: false
#           persistentVolume:
#             size: 1Gi
#             storageClass: gp2
#         minio:
#           enabled: false
#         kafka: 
#           enabled: true
#       releaseName: mimir-distributed
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: mimir
#   syncPolicy:
#     syncOptions:
#       - ServerSideApply=true



