apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.2.0
    chart: grafana
    helm:
      values: |
        grafana.ini:
          database:
            type: postgres
            host: postgres:5432
            ssl_mode: disable
        envFromSecret: grafana-database-secret
        persistence:
          enabled: false
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
