apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-scalable
  namespace: argocd
spec:
  project: default
  source:
    chart: loki 
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.46.0
    helm:
      values: |
        deploymentMode: SimpleScalable
        serviceAccount:
          annotations:
           eks.amazonaws.com/role-arn: arn:aws:iam::313616258649:role/mimir-sa
        loki:
          schemaConfig:
            configs:
              - from: "2026-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage_config:
            aws:
              region: us-east-1 
              bucketnames: loki-am-1
              s3forcepathstyle: false
          storage:
            type: s3
            bucketNames:
                chunks: loki-am-1
                ruler: loki-am-2
                admin: loki-am-3
            s3:
              region: us-east-1
          ingester:
              chunk_encoding: snappy  
          pattern_ingester:
            enabled: true       
          limits_config:
            volume_enabled: true
            retention_period: 672h
          compactor:
            retention_enabled: true 
            delete_request_store: s3
        gateway:
          service:
            type: LoadBalancer
        write:  
          persistence:  
            enabled: true
            storageClass:gp2
            size: 1Gi
        read: 
          autoscaling:
            minReplicas: 1
            maxReplicas: 2
          ingress:
            enabled: true
            ingressClassName: alb

      releaseName: loki-simple-scalable
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki
  syncPolicy:
    syncOptions:
      - ServerSideApply=true