# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: loki-scalable
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: loki 
#     repoURL: https://grafana.github.io/helm-charts
#     targetRevision: 6.46.0
#     helm:
#       values: |
#         deploymentMode: SimpleScalable
#         serviceAccount:
#           annotations:
#             eks.amazonaws.com/role-arn: arn:aws:iam::313616258649:role/LokiServiceAccountRole
#         loki:
#           schemaConfig:
#             configs:
#               - from: "2024-04-01"
#                 store: tsdb
#                 object_store: s3
#                 schema: v13
#                 index:
#                   prefix: loki_index_
#                   period: 24h
#           storage_config:
#             aws:
#               region: us-east-1 
#               bucketnames: loki-am-1 # Your actual S3 bucket name, for example, loki-aws-dev-chunks
#               s3forcepathstyle: false
#           ingester:
#               chunk_encoding: snappy
#           pattern_ingester:
#               enabled: true
#           limits_config:
#             allow_structured_metadata: true
#             volume_enabled: true
#             retention_period: 672h # 28 days retention
#           compactor:
#             retention_enabled: true 
#             delete_request_store: s3
#           ruler:
#             enable_api: true
#             storage:
#               type: s3
#               s3:
#                 region: us-east-1 
#                 bucketnames: loki-am-2 # Your actual S3 bucket name, for example, loki-aws-dev-ruler
#                 s3forcepathstyle: false
              

#           querier:
#               max_concurrent: 4

#           storage:
#               type: s3
#               bucketNames:
#                 chunks: "loki-am-1" # Your actual S3 bucket name (loki-aws-dev-chunks)
#                 ruler: "loki-am-2" # Your actual S3 bucket name (loki-aws-dev-ruler)
#               # admin: "loki-am-3" # Your actual S3 bucket name (loki-aws-dev-admin) - GEL customers only
#               s3:
#                 region: us-east-1 
#                 #insecure: false
#               # s3forcepathstyle: false
#         gateway:
#           service:
#             type: LoadBalancer
#         write:  
#           persistence:  
#             enabled: true
#             storageClass: gp2
#             storageClass: gp2
#             size: 1Gi
#         read: 
#           autoscaling:
#             minReplicas: 1
#             maxReplicas: 2
#           ingress:
#             enabled: true
#             ingressClassName: alb
#         minio:
#           enabled: false

#       releaseName: loki-simple-scalable
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: loki
#   syncPolicy:
#     syncOptions:
#       - ServerSideApply=true